version: '3'

services:
  db:
    image: postgres
  migration:
    build: .
    command: hy manage.hy migrate --settings=src.settings.local-docker
    volumes:
      - .:/app
    depends_on:
      - db
  load_fixtures:
    build: .
    command: hy manage.hy loaddata products/fixture.json --settings=src.settings.local-docker
    volumes:
      - .:/app
    depends_on:
      - migration
  web:
    build: .
    command: hy manage.hy runserver 0.0.0.0:8000 --settings=src.settings.local-docker
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migration
      - load_fixtures
